# Generated by Django 3.1.7 on 2021-05-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItem',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='ShippingModel',
            new_name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
